export const Database = [
    {
      id: 1,
      name: "Pink Donut",
      description: "Spicy tasty donut family",
      price: 10.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/pink_donut 1.png"),
      type: "p",
    },
    {
      id: 2,
      name: "Pink Donut",
      description: "Spicy tasty donut family",
      price: 20.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/tasty_donut 1.png"),
      type: "p",
    },
    {
      id: 3,
      name: "Floating Donut",
      description: "Spicy tasty donut family",
      price: 30.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/green_donut 1.png"),
      type: "float",
    },
    {
      id: 4,
      name: "Tasty Donut",
      description: "Spicy tasty donut family",
      price: 40.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/donut_yellow 1.png"),
      type: "float",
    },

    {
      id: 5,
      name: "Tasty Donut",
      description: "Spicy tasty donut family",
      price: 50.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/pink_donut 1.png"),
      type: "float",
    },

    {
      id: 6,
      name: "Tasty Donut",
      description: "Spicy tasty donut family",
      price: 50.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/pink_donut 1.png"),
      type: "float",
    },

    {
      id: 7,
      name: "Tasty Donut",
      description: "Spicy tasty donut family",
      price: 50,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/pink_donut 1.png"),
      type: "float",
    },
    {
      id: 8,
      name: "Tasty Donut",
      description: "Spicy tasty donut family",
      price: 50.00,
      info: "Order a Large Pizza but the size is the equivalent of a medium/small from other places at the same price range.",
      img: require("../assets/img/pink_donut 1.png"),
      type: "float",
    },
  ];